	! PROGRAM TO SORT A SET OF NUMBERS IN ASCENDING ORDER USING
	! BUBBLE SORT TECHNIQUE
	IMPLICIT NONE
	INTEGER, DIMENSION (100):: A
	INTEGER TEMP, I, J, N
	PRINT *, 'ENTER THE NUMBER OF TERMS'
	READ *, N
	PRINT *, 'ENTER THE VALUES'
	READ *, (A(I), I=1,N)
	PRINT *, 'THE NUMBERS ARRANGED IN ASCENDING ORDER ARE:'
	DO I=1,N
	DO J=I+1,N
	IF (A(I) .GT. A(J)) THEN
	TEMP = A(I)
	A(I) = A(J)
	A(J) = TEMP
	END IF
	END DO
	PRINT *, A(I)
	END DO
	END