	! PROGRAM OF LEAST SQUARE FIT
	IMPLICIT NONE
	REAL XAVG, YAVG, M, C
	INTEGER I, N
	INTEGER X(100), Y(100)
	M=0
	XAVG=0
	YAVG=0
	PRINT *, 'ENTER THE NUMBER OF DATA'
	READ *, N
	PRINT *, 'ENTER THE VALUES OF X'
	READ *, (X(I), I=1,N)
	PRINT *, 'ENTER THE VALUES OF Y'
	READ *, (Y(I), I=1,N)
	! TO FIND XAVG AND YAVG
	DO I=1,N
	XAVG = XAVG + X(I)
	YAVG = YAVG + Y(I)
	END DO
	XAVG = XAVG/N
	YAVG=YAVG/N
	! TO FIND SLOPE AND INTERCEPT
	DO I=1,N
	M = M + ((X(I)-XAVG)*Y(I)) ! SLOPE
	WRITE (47,*) X(I), Y(I)
	END DO
	C = YAVG - (M*XAVG) ! INTERCEPT
	PRINT *, 'THE SLOPE IS:',M
	PRINT *, 'THE INTERCEPT IS:',C
	END
