!	PROGRAM TO ADD 2 MATRICES
	IMPLICIT REAL*8 (A-H, O-Z)
	PARAMETER (L=50)
	DIMENSION A(L,L), B(L,L), C(L,L)
	PRINT *, 'ENTER THE DIMENSION OF THE MATRIX'
	READ *, N
	PRINT *, 'ENTER THE VALUES IN MATRIX A'
	READ *, ((A(I,J),J=1,N),I=1,N)
	PRINT *, 'ENTER THE VALUES IN MATRIX B'
	READ *, ((B(I,J),J=1,N),I=1,N)
!	ADDITION OF THE 2 MATRICES
	DO I=1,N
	DO J=1,N
	C(I,J) = 0.0D0
	C(I,J) = A(I,J) + B(I,J)
	END DO
	END DO
!	DISPLAYING THE RESULT
	DO I=1,N
	WRITE (*,*) (C(I,J),J=1,N)
	END DO
	END
