PROGRAM SIMPSON 
	!PROGRAM TO DEMONSTRATE SIMPSON'S 1/3RD RULE WHERE THE FUNCTION IS F(X) = X^2
IMPLICIT REAL*8 (A-H, O-Z)
	PRINT *, 'ENTER THE LOWER LIMIT(A) AND UPPER LIMIT(B)'
	READ *, A,B
	PRINT *, 'ENTER THE NO. OF DIVISIONS(N). "N" SHOULD BE EVEN'
	READ *, N
	R=N
	H = (B-A)/R
	RINTEG = 0.0D0
DO I = 1, N+1
	X = A + (I-1)*H
	FUNC = X*X
	IF((I .EQ. 1) .OR. (I .EQ. (N+1))) THEN
		RINTEG = RINTEG + FUNC
	ELSE
	IF (MOD(I,2) .EQ. (0.0D0)) THEN
		RINTEG = RINTEG + 4*FUNC
	ELSE
		RINTEG = RINTEG + 2*FUNC
	END IF
	END IF
END DO
	RINTEG = RINTEG * (H/3)
	PRINT *, 'THE RESULT IS:',RINTEG
END PROGRAM SIMPSON