	! PROGRAM TO FIND THE RESULT OF SIN SERIES EXPANSION
	IMPLICIT NONE
	REAL SUMM, POWER, X
	DOUBLE PRECISION PI
	INTEGER N, FACT, I, J, ADD, A
	PI = 4.0*ATAN(1.0)
	ADD = 1
	A = 1
	POWER = 1
	PRINT *, 'ENTER THE NUMBER OF TERMS N AND A VALUE FOR X'
	READ *, N, X
	X = PI/180.0
	SUMM = 0.0
	DO I=1,N
	FACT = 1
	DO J=1,A
	FACT = FACT*J
	END DO
	POWER = X**A
	SUMM = SUMM + (POWER/FACT)*ADD
	A = A+2
	ADD = ADD*(-1)
	END DO
	PRINT *, 'THE SUM OF THE SERIES IS:',SUMM
	END 
