!	PROGRAM TO FIND THE TRANSPOSE OF A SQUARE MATRIX
	IMPLICIT NONE
	INTEGER N, I, J
	REAL A(100,100), B(100,100)
	PRINT *, 'ENTER THE DIMENSION OF SQUARE MATRIX A'
	READ *, N
	PRINT *, 'ENTER THE VALUES IN MATRIX A'
	READ *, ((A(I,J),J=1,N),I=1,N)
!	FINDING THE TRANSPOSE
	DO I=1,N
	DO J=1,N
	B(J,I) = A(I,J)
	END DO
	END DO
!	DISPLAYING THE TRANSPOSED MATRIX
	PRINT *, 'THE TRANSPOSED MATRIX IS:'
	DO I=1,N
	WRITE (*,*) (B(I,J),J=1,N)
	END DO
	END
